services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"  # Gradio UI
    environment:
      - DB_USER=app_user
      - DB_PASSWORD=Password123!
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=semantic_search
    volumes:
      - ./:/app
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11.7-rc
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: semantic_search
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
