version: '3.8'

services:
  mariadb:
    image: mariadb:11.7-rc
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: semantic_search
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
