Output .gif demo.gif
Set FontSize 20
Set Width 1800
Set Height 1000
Type uv run -m app.cli video --help
Enter 1
Sleep 4s
Type uv run -m app.cli video list
Enter 1
Sleep 5s
Type uv run -m app.cli video create --id v5Y5ftlGNhU --title "High Performance Data Visualization for the Web" --meta="{\"event\": \"PyCon DE & PyData Berlin 2024\"}"
Enter 1
Sleep 15s
Type uv run -m app.cli video search "temporal durable execution with python"
Enter 1
Sleep 10s
Type uv run -m app.frontend
Enter 1
Sleep 7s
